config/routes.rb
Rails.application.routes.draw do

  get 'category/index'
  get 'category/show'
  get 'tags/index'
  get 'tags/show'
  #mount Ckeditor::Engine => '/ckeditor'
  #get 'all_tags/index'
  #get 'all_tags/show'
  #get 'caetgory/index'
  #get 'category/index'
  #get 'category/show'
  devise_for :users 


  resources :posts do
    resources :likes do
    collection do 
      get :search
    end
      resources :comments, only: [:create, :delete]
    end
    resources :tags, only: [:index, :show]
  end
   
  resources :posts do 
      resources :comments 
  end

  resources :categories do 
    resources :posts 
  end


  #root to: "categories#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "posts#index"

  #routes to access path 
  get 'users/:id', :to => 'user#show', :as => :user
  get '/category', :to => 'category#index'  
  get 'category/:id', :to => 'category#show'
  
end

app/models/category.rb
class Category < ApplicationRecord
   
   has_and_belongs_to_many :posts
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    if params[:category_id]
      @categories = Category.find params[:category_id]
      @posts = @category.posts 
    else 
      @posts = Post.all
    end
  end
  
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/category/index.html.erb
<div class="container">
    <div class="row"> 
    <div class="gallery col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h2 class="gallery">Category</h2>
    </div>

    <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6 filter hdpe">
        <% @categories.each do |category| %>
            <p class=tagname><%= link_to category.name, category_show_url %></p>
        <% end %> 
    </div>

    </div>
</div>

app/views/category/show.html.erb
 

<% @posts.each do |post| %> 
    <h4><%= post.title %></h4> 

    <p><%= post.text %></p>
<% end %>