config/routes.rb
Rails.application.routes.draw do

  get 'category/index'
  get 'category/show'
  get 'tags/index'
  get 'tags/show'
  #mount Ckeditor::Engine => '/ckeditor'
  #get 'all_tags/index'
  #get 'all_tags/show'
  #get 'caetgory/index'
  #get 'category/index'
  #get 'category/show'
  devise_for :users 


  resources :posts do
    resources :likes do
    collection do 
      get :search
    end
      resources :comments, only: [:create, :delete]
    end
    resources :tags, only: [:index, :show]
  end
   
  resources :posts do 
      resources :comments 
  end

  resources :categories do 
    resources :posts 
  end


  #root to: "categories#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "posts#index"

  #routes to access path 
  get 'users/:id', :to => 'user#show', :as => :user
  get '/category', :to => 'category#index'  
  get 'category/:id', :to => 'category#show'
  
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :text

    #has_many :taggings, dependent: :destroy
    #has_many :tags, through: :taggings 

    has_many :comments, dependent: :destroy
    belongs_to :user
   

    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    acts_as_taggable_on :tags
   
    #has_many :likes, dependent: :destroy
    #def already_likes?(post) 
        #self.likes.find(:all, :condition => ['post_id = ?', post.id]).size > 0
    #end
    has_and_belongs_to_many :categories

    def publish_month 
        published_at.strftime("%B %Y")
    end

    searchable do
        text :title, :text
        text :tag_list
        
        text :comments do 
            comments.map(&:post)
        end
        time :created_at 
    end

    has_many :likes
  
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :authenticate_user!, except: [:post, :index]
 

  # GET /posts
  # GET /posts.json
  def index
    @search = Post.search do 
      fulltext params[:search] 
      paginate(page: params[:page])
    end

    @posts = @search.results
    @tags = ActsAsTaggableOn::Tag.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.all
    
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post = current_user.posts.build
  end

  # User_list 

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #add category on post 

  def add_category 
    @post = Post.find(params[:id])
    @post.categories << Category.find(params[category_id])
  end

  def taggged 
    if params[:tag].present? 
      @post = Post.tagged_with(params[:tag])
    else 
      @post = Post.all 
    end
  end
  
  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text, :image, :user_id, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    #def tags_links(all_tags) 
        #all_tags.split(",").map{|tag| link_to tag.strip, tag_path(tag_strip) }.join(", ")
    #end

    def tag_cloud(all_tags, classes)
        max = all_tags.short_by(&:count).last 
        all_tags.each do |tag| 
            index = tag.count.to_f / max.count * (classes.size-1)
            yield(tag, classes[index.round])
        end
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "inputText">

    <div class="form-group col-md-4">
      <%= form.label :title %><br>
      <%= form.text_field :title, :placeholder => "title", :class => "form-control" %>
    </div>


  <div class="form-group">
    <%= form.label :image %><br> 
    <%= form.file_field :image, :class => 'btn-btn-primary' %>
  </div>

  <div class="form-group col-md-12">
    <%= form.label :text %><br>
    <%= form.text_area :text, :class => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, :placeholder => "write your story", :class => "form-control", :size => '50x20' %>
  </div>

  <br>
  <div class="form-group col-md-12">
    <%= form.label :tags %><br> 
    <%= form.text_field :tag_list, :class => "form-control" %> 
  </div>

  
  <div class="actions col-md-4">
    <%= form.submit"Make story", :class => "btn-btn primary" %>
  </div>
   </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="card" style="margin-top: 60px;">


  <div class="card-body"> 
    <% if @posts %> 
  <% @posts.in_groups_of(3, false).each do |row| %> 
   <div class="row">
    <% row.each do |post| %> 
  
     <div class="col-md-4">

     <h3 class="card-title">
        <%= link_to post.title, post, {:style=>'color:#85a3e0;', :class => "css_class"} %>
     </h3>

      <% if post.image.file? %> 
          <%= image_tag post.image.url, :size => '250x150' %> 
      <% else %> 
          No image File!
      <% end %>

      <p class="card-subtitle mb-2 text-muted">
          <%= post.user.username %> 
      </p>

      <p class="card-subtitle mb-2 text-muted">
          <%= post.created_at.strftime("#{post.created_at.day.ordinalize} %B %Y") %>
      </p>

      <%= link_to 'read more', post, :class => "card-link" %>
    </div>
    <% end %> 
   </div>

   <% end %>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="Newpost"
    <div class="title"> 
        <h4>New Post</h4>
    </div>

    <%= render 'form', post: @post %>
<div>

app/views/posts/show.html.erb
<div class="container text-center Bodyname">
  <div class="col-sm-12">
  
    <h1><%= @post.title %></h1>
    
    <div class="user"> 
      <p><%= @post.user.username %></p>
    </div>

     <% if @post.image.file? %> 
      <%= image_tag @post.image.url, :size => '900x550' %>
    <% else %> 
      
      <% end %>

    <br>
    <div class="col-6">    
      <p class="show">
        <%= @post.text %>
       </p>
    </div>
   

    <div class="item">
      <div class="item-content-block tags">
        <p><%= @post.tag_list %></p>
      </div>
    </div>

    <div classs="likeName">
        <%= link_to 'favorite', post_path(@post), method: :post, :class => 'btn btn-primary' %>
    </div>
    
    <div class="CommentName container text-left">
        <%= @comment.count %>
        <%= render 'comment/comments' %>

        <p>Create respond: </p> 
        <%= render 'comment/form' %> 
    </div>

  </div> 
       <%= link_to 'Back', posts_path, :class => 'btn btn-primary' %>
    </div>
</div>

app/views/posts/tags.html.erb
<div class="container text-center">
  <div class="col-sm-12">
  
    <h1><%= @post.title %></h1>

     <% if @post.image.file? %> 
      <%= image_tag @post.image.url, :size => '600x550' %>
    <% else %> 
      
      <% end %>

    <br>
    <div class="col-6">    
      <p class="show">
        <%= @post.text %>
       </p>
    </div>

    <div class="container"> 
    <% @post.comments.each do |comment| %>
      <%= render @comment.body %>

      <%= render :partial => "comment/form", :locals => {:comment => comment } %>  
    <% end %>
    </div> 

     <p><%= @post.all_tags %></p>

       <%= link_to 'Back', posts_path, :class => 'btn btn-light' %>

    <% if can? :update, @post %> 
      <%= link_to 'Edit', edit_post_path, :class => 'btn btn-light' %>
    <% end %> 
     
    <% if can? :delete, @post %>
      <%= link_to 'Delete', @post, method: :delete, :data => { confirm: 'are you sure ?' }, :class => 'btn btn-light' %>
    <% end %>
    </div>
</div>